### ISSUE TITLE
App crashed

### ISSUE THREAD

**Issue by Seinuh** [lucasvdh/codes.lucasvdh.android-tv#2]
app crashed on homey 2023, a fresh install will not fix this

**Comment by GazPaz** [comment]
Hi Lucas. The homey app has crashed out of the blue. I have tried a few resolutions including removing all devices and reinstalling the app, and still crashing. Any help would be appreciated. Gary

**Comment by lucasvdh** [comment]
I think this is due to a memory leak in the connect/reconnect logic. I'm working on a fix.

**Comment by ratcliffeg** [comment]
Same here on both Official and test.
Homey Pro 2023 10.0.4-rc.10
800780ad-af3b-4dc2-9f2b-6e92de6639bb

**Comment by lucasvdh** [comment]
Hi @Seinuh, @GazPaz and @ratcliffeg,

This issue should be resolved from version `v0.5.2`, please let me know if this is not the case or if you have any questions.
