### ISSUE TITLE
[Issue] Keeps craching 

### ISSUE THREAD

**Issue by tobias-moeller** [lucasvdh/codes.lucasvdh.android-tv#7]
My apps keeps crashing, i tried to restart the app but it dosent work.

I have submitted the issue, and should give the following code to the developer.
babac07a-7ab7-4175-80dd-f07fda4576d6

**Comment by lucasvdh** [comment]
Hi @tobias-moeller,

This issue should be resolved from version `v0.5.2`, please let me know if this is not the case or if you have any questions.
